import About from "@/components/About";
import Contact from "@/components/Contact";
import Education from "@/components/Education";
import Experience from "@/components/Experience";
import Hero from "@/components/Hero";
import Portfolio from "@/components/Portfolio";
import Services from "@/components/Services";
import Skills from "@/components/Skills";
import Testimonials from "@/components/Testimonials";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useState, useEffect, useContext } from "react";
import PreLoader from "@/components/PreLoader";

export default function Home() {
  const [toggle, setToggle] = useState(false);

  useEffect(() => {
    const storedToggle = JSON.parse(localStorage.getItem("toggle"));
    setToggle(storedToggle || false);
  }, []);

  const handleToggle = (newToggle) => {
    setToggle(newToggle);
    localStorage.setItem("toggle", JSON.stringify(newToggle));
  };

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => setLoading(false), 5500); // simulate loading for 3 seconds
    return () => clearTimeout(timer);
  }, []);

  return (
    <div className={toggle ? "dark" : ""}>
      <Head>
        <title>ANAKIN'S Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-primary-white dark:bg-primary-black">
        {loading ? (
          <PreLoader />
        ) : (
          <>
            <Navbar onToggle={handleToggle} initialToggle={toggle} />
            <Hero />
            <About />
            <Education />
            <Experience />
            <Services />
            <Skills />
            <Portfolio />
            <Testimonials />
            <Contact />
            <Footer />
          </>
        )}
      </main>
    </div>
  );
}
